### ISSUE TITLE
基礎ELK

### ISSUE THREAD

**Issue by mikeqoo1** [mikeqoo1/Note#12]
ElasticSearch + Kibana + IK Plusin

先著重在ElasticSearch

**Comment by siaochanwu** [comment]
- https://lufor129.medium.com/elk-%E5%AF%A6%E4%BD%9C%E5%88%86%E6%95%A3%E5%BC%8Flog%E6%8E%A1%E9%9B%86%E7%B3%BB%E7%B5%B1-d3e729624af4
